fix: rewrite wan-event hook for /opt path with existence check

diff --git a/router/jffs/scripts/wan-event b/router/jffs/scripts/wan-event
--- a/router/jffs/scripts/wan-event
+++ b/router/jffs/scripts/wan-event
@@ -1,17 +1,12 @@
 #!/bin/sh
 
-###################################################################################################
-# wan-event - Asuswrt-Merlin hook invoked when WAN state changes
-# Arguments: $1 = WAN unit (0, 1, ...), $2 = event type
-###################################################################################################
-
 PATH=/opt/sbin:/opt/bin:/usr/sbin:/usr/bin:/sbin:/bin
+VPD_SCRIPT="/opt/vpn-director/vpn-director.sh"
 
-# Skip if Entware not ready (during early boot)
-[ -x /opt/bin/bash ] || exit 0
+[ "$2" = "connected" ] || exit 0
 
-case "$2" in
-    connected)
-        /jffs/scripts/vpn-director/vpn-director.sh apply
-        ;;
-esac
+if [ -x "$VPD_SCRIPT" ]; then
+    "$VPD_SCRIPT" apply
+else
+    logger -t "wan-event" "vpn-director not found at $VPD_SCRIPT"
+fi
